### ISSUE TITLE
No more updates?

### ISSUE THREAD

**Issue by sjoerd222888** [yyolk/rpi-archlinuxarm#1]
The latest version on docker is one year old. And unfortunatly it not possible to update the package eaily due to:
```

Step 3/46 : RUN pacman -Syu                                                                                                                                                 
 ---> Running in 4ced541f0aa2                                                                                                                                                   
:: Synchronizing package databases...                                                                                                                                            
downloading core.db...                                                                                                                                                              
downloading extra.db...                                                                                                                                                                
downloading community.db...
downloading alarm.db...
downloading aur.db...
:: Starting full system upgrade...
:: Replace dirmngr with core/gnupg? [Y/n] y
:: Replace libdbus with core/dbus? [Y/n] :: Replace libusbx with core/libusb? [Y/n] resolving dependencies...
:: looking for inter-conflicts...
:: dbus and libdbus are in conflict
dbus and libdbus are in conflict. Remove libdbus? [y/N] error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
The command '/bin/sh -c pacman -Syu' returned a non-zero code: 1
```

Your slogan with daily-builds is not true any longer I guess. Could you maybe create a newer image if you have the infrastructure still available?

**Comment by sjoerd222888** [comment]
I tried to use your Dockerfile to create a new image but I get the following error:

```
Step 1/7 : FROM base/arch
latest: Pulling from base/arch
a3ed95caeb02: Pull complete 
f5b0e81b589e: Pull complete 
Digest: sha256:36d67f448b8c0028c40aa12b0bfb0287e882ea9741f5688e359a3d9961bf692e
Status: Downloaded newer image for base/arch:latest
 ---> 8468df3f1056
Step 2/7 : RUN mkdir /run/shm
 ---> Running in 4a26430b6bb0
standard_init_linux.go:187: exec user process caused "exec format error"
The command '/bin/sh -c mkdir /run/shm' returned a non-zero code: 1
```

If you start from arch/base it's not ARM right? On what kind of machine do I need to build the image. The error message above comes when I run `docker build -t rpi-archlinuxarm .` on a raspberry pi.

**Comment by yyolk** [comment]
hey @sjoerd222888 I would love to help you out in getting a build to work locally for you. You're right I've not been updating this for a while - the PI that was doing the builds is lost in storage at the moment :(

How can I help?

**Comment by sjoerd222888** [comment]
Thanks for your answer.

 I did some research in the meantime and succeeded creating my own arch images using 
- https://github.com/moby/moby/blob/master/contrib/mkimage-arch.sh
- https://github.com/moby/moby/blob/master/contrib/mkimage-arch-pacman.conf

Running  `./mkimage-arch.sh` on my Raspberry PI yielded a compatible arch image that is also quite small (357MB).
Btw. I used this (in the meantime slightly outdated) [blogpost](http://www.wzzrd.com/2015/08/building-arch-linux-docker-base-image.html) as a guideline to start with. Most extra steps described there are not required any more.

**Comment by yyolk** [comment]
@sjoerd222888 glad you were able to get it going! 357MB sounds bigger than I am used to (last image on docker hub was 137MB a year ago...) but have to verify this by getting this running again.
![image](https://user-images.githubusercontent.com/134478/30082405-4a25d71a-9250-11e7-9033-66bdd6169324.png)

Thank you for the links!
